### ISSUE TITLE
Direct operations with batch file

### ISSUE THREAD

**Issue by hellishvictor** [RedDocMD/cork#15]
Hi, it would awesome if were possible to make direct operations on a single line, so it can be used with a batch file, something like:
`cork 0x4DEE72 + 0x18CF5 >filename.txt`
Actually it outputs :
```
error: Found argument '0x4DEE72' which wasn't expected, or isn't valid in this context

USAGE:
    cork [OPTIONS]

For more information try --help
```
Cheers

**Comment by RedDocMD** [comment]
Hi!
`cork` does have the `-e` flag to evaluate the first arg as an expression and print the result to stdout. So:
```
~ via 🐍 v3.8.10
❯ cork -e '0x4DEE72 + 0x18CF5'
0x4f7b67
```
To save it in a file, you can do `cork -e '0x4DEE72 + 0x18CF5' > filename.txt`.
