### ISSUE TITLE
Define a config file to customize cork's behavior

### ISSUE THREAD

**Issue by ptosi** [RedDocMD/cork#2]
Define the format for a file holding the user's configuration preferences and implement the logic to read and parse that file at start-up.

Preferably, the file should be expected to be found under `${XDG_CONFIG_HOME}/cork/`, as per the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/).

**Comment by RedDocMD** [comment]
I designed cork to be Windows-compatible as well. So, I am guessing following the XDG specs won't be such a good idea.

**Comment by RedDocMD** [comment]
The config file might have:
- Enable/disable header
- Default output format
- Prompt (because some people simpler prompts, others more fancier ones)

@ptosi, do you have something else you want to see as a config?
