### ISSUE TITLE
Allow disabling the welcome message

### ISSUE THREAD

**Issue by ptosi** [RedDocMD/cork#3]
The welcome message is cute:
```
$ cork
Welcome to cork - a calculator for hex-lovers!
Press Ctrl + D to exit.
cork> 
```
but is far from being crucial: there should be a way to disable it, if desired.

A good way would be through an option in a config file (see #2).

**Comment by RedDocMD** [comment]
True. Actually now that you pointed it out, I should add the GPLv2 header, as recommended [here](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html#SEC4).
