### ISSUE TITLE
Add support for one-off operations through `argv`

### ISSUE THREAD

**Issue by ptosi** [RedDocMD/cork#4]
Cork currently ignores command-line arguments; instead, it could be extended to accept an expression, compute and print it, and exit.

For example:
```
$ cork 0x10 + 0x10
0x20
$ cork
Welcome to cork - a calculator for hex-lovers!
Press Ctrl + D to exit.
cork> 0x10 + 0x10
0x20
cork>
```
(note that, in the first case, cork returns immediately)

**Comment by RedDocMD** [comment]
That would also be quite neat, although I think we should have a `-c` flag to accept the expression inline.
