### ISSUE TITLE
Support separators in long numbers

### ISSUE THREAD

**Issue by ptosi** [RedDocMD/cork#6]
For readability of the numbers, it is sometimes desired to add separators to long numbers (for example, writing `0x3000_0000` to avoid confusion with `0x3000000` or `0x300000000`); could this be supported by cork? As long as those separators aren't valid operators, it should simply mean stripping arguments from expected separators before converting them to integers.

As an illustration, consider the following:
```
cork> 0x3000_0000 + 0x200_0000
Failed to parse "0x3000_0000 + 0x200_0000":  --> 1:7
  |
1 | 0x3000_0000 + 0x200_0000
  |       ^---
  |
  = expected EOI, add, subtract, multiply, divide, rem, lshift, or rshift
  ```
  
  Although this is requested for hex numbers, I guess it would also be valid for other bases and characters other than `_`: for example `10'000'000`, `10,000,000`? The hex case being the most interesting, of course.

**Comment by RedDocMD** [comment]
Thanks for the issues, @ptosi!
I am sticking to having underscore as a separator (since many languages support that).
